#########################################################
# Below all fixed settings for doorbell PCB
#########################################################
substitutions:
  devicename: meek-doorbell
  friendly: ESPHome Doorbell
  ip: 192.168.100.211
  neopixel: GPIO02 # (D4)
  gpio_relay4: GPIO13 # (D7)

#########################################################
# Everything below can be copy/paste without problem
#########################################################
esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  fast_connect: true
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.100.1
    subnet: 255.255.255.0
    dns1: 192.168.100.1
  ap:
    ssid: ${devicename}
    password: !secret password
    channel: 4

api:
  encryption:
    key: !secret api_key
  reboot_timeout: 15min

time:
  - platform: homeassistant
    id: homeassistant_time

preferences:
  flash_write_interval: 1min
  
logger:
  level: DEBUG
  
ota:
  safe_mode: true
  password: !secret password

button:
  - platform: factory_reset
    name: "${friendly} - reset"

i2c:
  sda: GPIO04
  scl: GPIO05

light:
  - platform: neopixelbus
    default_transition_length: 0s
    type: GRB
    variant: 800KBPS
    pin: ${neopixel}
    num_leds: 1
    name: "${friendly} - Neopixel"
    restore_mode: ALWAYS_ON
    id: neopixel

binary_sensor:
  - platform: gpio
    pin:
      number: ${gpio_relay4}
      inverted: true
    name: "${friendly} - Doorbell"

switch:
  - platform: safe_mode
    name: "${friendly} - safe mode"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly} - ip"
      icon: mdi:lan
    ssid:
      name: "${friendly} - ssid"
      icon: mdi:lan
    bssid:
      name: "${friendly} - bssid"
      icon: mdi:lan
    mac_address:
      name: "${friendly} - mac"
      icon: mdi:lan

  - platform: version
    name: "${friendly} - Version"
    hide_timestamp: true

sensor:
  - platform: wifi_signal
    name: "${friendly} - wifi Signal"
    update_interval: 5min

  - platform: uptime
    name: "${friendly} - Uptime"
    update_interval: 5min
